version: '3.8'

services:
  weather-app:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENV=production
    volumes:
      - ./weatherForcastingCalculator/Data:/app/weatherForcastingCalculator/Data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development override
  weather-app-dev:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "5000:5000"
    environment:
      - PYTHONPATH=/workspace
      - ENV=development
    volumes:
      - .:/workspace
      - /workspace/.devcontainer
    command: tail -f /dev/null  # Keep container running for development